# Generated by Django 4.1.1 on 2022-09-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=250)),
                ('birthday', models.DateField()),
                ('joindate', models.DateField()),
                ('city', models.CharField(max_length=250)),
            ],
        ),
    ]
