# Generated by Django 4.1.1 on 2022-10-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linkslist',
            fields=[
                ('userid', models.IntegerField()),
                ('linkid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('urlpath', models.CharField(blank=True, max_length=50)),
                ('dialog', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('userid', models.IntegerField()),
                ('todoid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('start', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=250)),
                ('done', models.BooleanField()),
                ('dialog', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='dashuser',
            name='userimage',
            field=models.ImageField(blank=True, upload_to='userimages/'),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='city',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='country',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='joindate',
            field=models.DateField(blank=True),
        ),
    ]
