# Generated by Django 4.1.1 on 2022-09-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashuser',
            name='userimage',
            field=models.ImageField(blank=True, upload_to='userimages/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='city',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='country',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='joindate',
            field=models.DateField(blank=True),
        ),
    ]
