# Generated by Django 4.1.1 on 2022-10-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0002_linkslist_todolist_dashuser_userimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='newname',
            field=models.TextField(blank=True),
        ),
    ]
