# Generated by Django 4.1.1 on 2022-09-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0002_dashuser_userimage_alter_dashuser_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashuser',
            name='userimage',
            field=models.ImageField(blank=True, upload_to='userimages/'),
        ),
    ]
