# Generated by Django 4.1.1 on 2022-10-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0003_todolist_newname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashuser',
            name='userimage',
            field=models.ImageField(blank=True, null=True, upload_to='userimages/'),
        ),
    ]
